sonar.projectKey=locaccm_calendarManagement
sonar.organization=locaccm

sonar.sources=src

sonar.tests=src/tests 
sonar.test.inclusions=**/*.test.ts  

sonar.javascript.lcov.reportPaths=./coverage/lcov.info

sonar.exclusions=src/tests/**/*

# Exclude files from coverage calculation (same as in Jest config)
sonar.coverage.exclusions=src/app.ts,src/routes/eventRoutes.ts,src/data-source.ts

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=calendarManagement
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
